### ISSUE TITLE
non-schema validation

### ISSUE THREAD

**Issue by fuenkchen** [nzzdev/Q-server#36]
At the moment we just use the tool-specific schema to validate if a q item for creating/saving/getting rendering info. Idea is to have other validation mechanisms for Q editor. One example: tool election seats could have a check if total seats is less than number seats of all parties.
Implementation idea: specify in the tool config an endpoint for further validation.

**Comment by benib** [comment]
Good Idea. Some problems that would have to be solved:
- If we validate from Q-editor there is the problem of consistency of the result. If user changes data while while the validation request is on its way it's hard to match the result against the current data once the validation result arrives. Blocking the UI during validation is not nice.
- We could validate in Q server only on save and show a (general) error message if the validation fails. This would be suboptimal for the user as the form looks valid until save response is back.

One solution would result in quite some requests to be sent during editing could probably be something like this:
- implement UI in Q editor to clearly show ongoing validation/valid/invalid state on different levels.
- send subobjects/array entries/single properties to the validation endpoint separately, that way we could indicate the ongoing validation per entry and it's easier to match the response to one entry. we can use Aurelia's attached/detached element lifecycle methods to setup and teardown the validation cycles per schema-editor element.
